### ISSUE TITLE
Span EPERM Issue

### ISSUE THREAD

**Issue by vokeio** [mafintosh/respawn#12]
I am not sure what the issue is here. But I don't think it should be throwing a permissions issue when setting the UID field. Any way I can help let me know.

```
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EPERM
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at loop (/Users/Alex/code/systems/alive/node_modules/respawn/index.js:106:17)
    at Monitor.start (/Users/Alex/code/systems/alive/node_modules/respawn/index.js:180:3)
    at Object.exports.add (/Users/Alex/code/systems/alive/index.js:173:10)
    at Object.<anonymous> (/Users/Alex/code/systems/alive/test.js:15:7)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
```

**Comment by mafintosh** [comment]
isn't this being emitted as a error on the monitor?

**Comment by AlexanderElias** [comment]
I am not sure. I will create an example and post it. Also the monitor starts when running the script with sudo.
