### ISSUE TITLE
node searched in relative path

### ISSUE THREAD

**Issue by OoDeLally** [mafintosh/respawn#21]
Im launching my server this way:
```
node --expose_gc ./node_modules/.bin/grunt server:local
```
And get the following error:
```
Error: Cannot find module '/home/oodelally/backend/node'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
module.js:491
    throw err;
```
So it seems that `node` is not taken from the environment, but from the current directory.

-------------------------------------------------------
More details if needed:
-------------------------------------------------------

package.json:
```
  "scripts": {
    "start": "node ./code/server/monitor.js node --expose_gc ./node_modules/.bin/grunt server:local"
  }
```

monitor.js:
```

'use strict'

const respawn = require('respawn')
const _ = require('lodash')

const args = _.drop(process.argv, 2)

const monitor = respawn(args, {
  name: 'server monitor',    // set monitor name
  env: process.env, // set env vars
  cwd: '.',              // set cwd
  maxRestarts: 10,       // how many restarts are allowed within 60s
                         // or -1 for infinite restarts
  sleep:[1000, 2000, 5000, 10000], // time to sleep between restarts,
  kill:30000,            // wait 30s before force killing after stopping
  stdio: 'pipe',          // forward stdio options
  fork: true             // fork instead of spawn
})

monitor.on('stdout', (data) => {
  process.stdout.write(data)
})

monitor.on('stderr', (data) => {
  process.stderr.write(data)
})

monitor.start() // spawn and watch

```

**Comment by mafintosh** [comment]
Did you mean to open the issue here? This error is unrelated to respawn

**Comment by 01binary** [comment]
Just hit the same issue. The source of the confusion is that when `fork: true` is set, respawn tries to load a node module instead of launching an executable. I don't understand why.

i.e. error above occurs because the author is expecting respawn to find node.exe, but respawn is actually looking for a node module called node.js in current directory, PATH, and any other directory it checks for node modules.

**Comment by 01binary** [comment]
Confirmed that adding fork option does change the API entirely, so you are supposed to specify node module name as target, and it's possible to pass Node path and Node args separately in options for `fork` (see docs).
